dsr1-fp4-mi355x-sglang:
  image: lmsysorg/sglang:v0.5.6.post2-rocm700-mi35x
  model: amd/DeepSeek-R1-0528-MXFP4-Preview
  model-prefix: dsr1
  runner: mi355x
  precision: fp4
  framework: sglang
  multinode: false
  seq-len-configs:
  - isl: 1024
    osl: 1024
    search-space:
    - { tp: 4, conc-start: 4, conc-end: 64 }
    - { tp: 8, conc-start: 4, conc-end: 64 }
  - isl: 1024
    osl: 8192
    search-space:
    - { tp: 8, conc-start: 4, conc-end: 64 }
  - isl: 8192
    osl: 1024
    search-space:
    - { tp: 8, conc-start: 4, conc-end: 64 }

dsr1-fp8-mi300x-sglang:
  image: rocm/7.0:rocm7.0_ubuntu_22.04_sgl-dev-v0.5.2-rocm7.0-mi30x-20250915
  model: deepseek-ai/DeepSeek-R1-0528
  model-prefix: dsr1
  runner: mi300x
  precision: fp8
  framework: sglang
  multinode: false
  seq-len-configs:
  - isl: 1024
    osl: 1024
    search-space:
    - { tp: 8, conc-start: 4, conc-end: 64 }
  - isl: 1024
    osl: 8192
    search-space:
    - { tp: 8, conc-start: 4, conc-end: 64 }
  - isl: 8192
    osl: 1024
    search-space:
    - { tp: 8, conc-start: 4, conc-end: 64 }

dsr1-fp8-mi325x-sglang:
  image: rocm/7.0:rocm7.0_ubuntu_22.04_sgl-dev-v0.5.2-rocm7.0-mi30x-20250915
  model: deepseek-ai/DeepSeek-R1-0528
  model-prefix: dsr1
  runner: mi325x
  precision: fp8
  framework: sglang
  multinode: false
  seq-len-configs:
  - isl: 1024
    osl: 1024
    search-space:
    - { tp: 8, conc-start: 4, conc-end: 64 }
  - isl: 1024
    osl: 8192
    search-space:
    - { tp: 8, conc-start: 4, conc-end: 64 }
  - isl: 8192
    osl: 1024
    search-space:
    - { tp: 8, conc-start: 4, conc-end: 64 }

dsr1-fp8-mi355x-sglang:
  image: rocm/7.0:rocm7.0_ubuntu_22.04_sgl-dev-v0.5.2-rocm7.0-mi35x-20250915
  model: deepseek-ai/DeepSeek-R1-0528
  model-prefix: dsr1
  runner: mi355x
  precision: fp8
  framework: sglang
  multinode: false
  seq-len-configs:
  - isl: 1024
    osl: 1024
    search-space:
    - { tp: 8, conc-start: 4, conc-end: 64 }
  - isl: 1024
    osl: 8192
    search-space:
    - { tp: 8, conc-start: 4, conc-end: 64 }
  - isl: 8192
    osl: 1024
    search-space:
    - { tp: 8, conc-start: 4, conc-end: 64 }

gptoss-fp4-mi300x-vllm:
  image: rocm/7.0:rocm7.0_ubuntu_22.04_vllm_0.10.1_instinct_20250927_rc1
  model: openai/gpt-oss-120b
  model-prefix: gptoss
  runner: mi300x
  precision: fp4
  framework: vllm
  multinode: false
  seq-len-configs:
  - isl: 1024
    osl: 1024
    search-space:
    - { tp: 1, conc-start: 64, conc-end: 64 }
    - { tp: 2, conc-start: 4, conc-end: 64 }
    - { tp: 4, conc-start: 4, conc-end: 64 }
    - { tp: 8, conc-start: 4, conc-end: 16 }
  - isl: 1024
    osl: 8192
    search-space:
    - { tp: 1, conc-start: 64, conc-end: 64 }
    - { tp: 2, conc-start: 4, conc-end: 64 }
    - { tp: 4, conc-start: 4, conc-end: 64 }
    - { tp: 8, conc-start: 4, conc-end: 16 }
  - isl: 8192
    osl: 1024
    search-space:
    - { tp: 1, conc-start: 4, conc-end: 64 }
    - { tp: 2, conc-start: 4, conc-end: 64 }
    - { tp: 4, conc-start: 4, conc-end: 64 }
    - { tp: 8, conc-start: 4, conc-end: 16 }

gptoss-fp4-mi325x-vllm:
  image: rocm/7.0:rocm7.0_ubuntu_22.04_vllm_0.10.1_instinct_20250927_rc1
  model: openai/gpt-oss-120b
  model-prefix: gptoss
  runner: mi325x
  precision: fp4
  framework: vllm
  multinode: false
  seq-len-configs:
  - isl: 1024
    osl: 1024
    search-space:
    - { tp: 1, conc-start: 4, conc-end: 64 }
    - { tp: 2, conc-start: 4, conc-end: 64 }
    - { tp: 4, conc-start: 4, conc-end: 64 }
    - { tp: 8, conc-start: 4, conc-end: 64 }
  - isl: 1024
    osl: 8192
    search-space:
    - { tp: 1, conc-start: 64, conc-end: 64 }
    - { tp: 2, conc-start: 4, conc-end: 64 }
    - { tp: 4, conc-start: 64, conc-end: 64 }
    - { tp: 8, conc-start: 4, conc-end: 64 }
  - isl: 8192
    osl: 1024
    search-space:
    - { tp: 1, conc-start: 4, conc-end: 64 }
    - { tp: 2, conc-start: 4, conc-end: 8 }
    - { tp: 4, conc-start: 4, conc-end: 8 }
    - { tp: 8, conc-start: 4, conc-end: 16 }

gptoss-fp4-mi355x-vllm:
  image: rocm/7.0:rocm7.0_ubuntu_22.04_vllm_0.10.1_instinct_20250927_rc1
  model: openai/gpt-oss-120b
  model-prefix: gptoss
  runner: mi355x
  precision: fp4
  framework: vllm
  multinode: false
  seq-len-configs:
  - isl: 1024
    osl: 1024
    search-space:
    - { tp: 1, conc-start: 4, conc-end: 128 }
    - { tp: 4, conc-start: 4, conc-end: 8 }
    - { tp: 8, conc-start: 4, conc-end: 16 }
  - isl: 1024
    osl: 8192
    search-space:
    - { tp: 1, conc-start: 4, conc-end: 128 }
    - { tp: 4, conc-start: 4, conc-end: 8 }
    - { tp: 8, conc-start: 4, conc-end: 16 }
  - isl: 8192
    osl: 1024
    search-space:
    - { tp: 1, conc-start: 4, conc-end: 128 }
    - { tp: 4, conc-start: 4, conc-end: 4 }
    - { tp: 8, conc-start: 4, conc-end: 8 }

dsr1-fp4-mi355x-atom:
  image: rocm/atom:nightly_gfx950_202601180240
  model: amd/DeepSeek-R1-0528-MXFP4-Preview
  model-prefix: dsr1
  runner: mi355x-p01-g42
  precision: fp4
  framework: atom
  multinode: false
  seq-len-configs:
  - isl: 1024
    osl: 1024
    search-space:
    - { tp: 4, ep: 1, conc-start: 4, conc-end: 128 }
    - { tp: 8, ep: 1, conc-start: 4, conc-end: 128 }
  - isl: 1024
    osl: 8192
    search-space:
    - { tp: 4, ep: 1, conc-start: 4, conc-end: 128 }
    - { tp: 8, ep: 1, conc-start: 4, conc-end: 128 }
  - isl: 8192
    osl: 1024
    search-space:
    - { tp: 4, ep: 1, conc-start: 4, conc-end: 128 }
    - { tp: 8, ep: 1, conc-start: 4, conc-end: 128 }

dsr1-fp8-mi300x-atom:
  image: rocm/atom:nightly_gfx950_202601170238
  model: deepseek-ai/DeepSeek-R1-0528
  model-prefix: dsr1
  runner: mi300x-tw033
  precision: fp8
  framework: atom
  multinode: false
  seq-len-configs:
  - isl: 1024
    osl: 1024
    search-space:
    - { tp: 8, conc-start: 4, conc-end: 4 }
  - isl: 1024
    osl: 8192
    search-space:
    - { tp: 8, conc-start: 4, conc-end: 4 }
  - isl: 8192
    osl: 1024
    search-space:
    - { tp: 8, conc-start: 4, conc-end: 4 }

dsr1-fp8-mi355x-atom:
  image: rocm/atom:nightly_gfx950_202601180240
  model: deepseek-ai/DeepSeek-R1-0528
  model-prefix: dsr1
  runner: mi355x-p01-g42
  precision: fp8
  framework: atom
  multinode: false
  seq-len-configs:
  - isl: 1024
    osl: 1024
    search-space:
    - { tp: 8, ep: 1, conc-start: 4, conc-end: 128 }
  - isl: 1024
    osl: 8192
    search-space:
    - { tp: 8, ep: 1, conc-start: 4, conc-end: 128 }
  - isl: 8192
    osl: 1024
    search-space:
    - { tp: 8, ep: 1, conc-start: 4, conc-end: 128 }

gptoss-fp4-mi300x-atom:
  image: rocm/atom:nightly_gfx950_202601170238
  model: openai/gpt-oss-120b
  model-prefix: gptoss
  runner: mi300x-tw033
  precision: fp4
  framework: atom
  multinode: false
  seq-len-configs:
  - isl: 1024
    osl: 1024
    search-space:
    - { tp: 1, conc-start: 4, conc-end: 128 }
    - { tp: 8, conc-start: 4, conc-end: 4 }
  - isl: 1024
    osl: 8192
    search-space:
    - { tp: 1, conc-start: 4, conc-end: 4 }
    - { tp: 8, conc-start: 4, conc-end: 4 }
  - isl: 8192
    osl: 1024
    search-space:
    - { tp: 1, conc-start: 4, conc-end: 4 }
    - { tp: 8, conc-start: 4, conc-end: 4 }

gptoss-fp4-mi355x-atom:
  image: rocm/atom:nightly_gfx950_202601180240
  model: openai/gpt-oss-120b
  model-prefix: gptoss
  runner: mi355x-p01-g42
  precision: fp4
  framework: atom
  multinode: false
  seq-len-configs:
  - isl: 1024
    osl: 1024
    search-space:
    - { tp: 1, ep: 1, conc-start: 4, conc-end: 128 }
    - { tp: 8, ep: 1, conc-start: 4, conc-end: 128 }
  - isl: 1024
    osl: 8192
    search-space:
    - { tp: 1, ep: 1, conc-start: 4, conc-end: 128 }
    - { tp: 8, ep: 1, conc-start: 4, conc-end: 128 }
  - isl: 8192
    osl: 1024
    search-space:
    - { tp: 1, ep: 1, conc-start: 4, conc-end: 128 }
    - { tp: 8, ep: 1, conc-start: 4, conc-end: 128 }

qwen3.235b-fp8-mi355x-vllm:
  image: rocm/vllm-dev:nightly
  model: Qwen/Qwen3-235B-A22B-Instruct-2507-FP8
  model-prefix: qwen3.235b
  runner: mi355x-m15-17
  precision: fp8
  framework: NA
  multinode: false
  seq-len-configs:
  - isl: 1024
    osl: 1024
    search-space:
    - { tp: 4, conc-start: 4, conc-end: 128 }

qwencoder3.480b-fp8-mi355x-vllm:
  image: rocm/vllm-dev:nightly
  model: Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8
  model-prefix: qwencoder3.480b
  runner: mi355x-m15-17
  precision: fp8
  framework: NA
  multinode: false
  seq-len-configs:
  - isl: 1024
    osl: 1024
    search-space:
    - { tp: 4, conc-start: 4, conc-end: 128 }

kimik2.inst0905-fp8-mi355x-vllm:
  image: rocm/vllm-dev:nightly
  model: moonshotai/Kimi-K2-Instruct-0905
  model-prefix: kimik2.inst0905
  runner: mi355x-m15-17
  precision: fp8
  framework: NA
  multinode: false
  seq-len-configs:
  - isl: 1024
    osl: 1024
    search-space:
    - { tp: 8, conc-start: 4, conc-end: 128 }

kimik2think-int4-mi355x-vllm:
  image: rocm/vllm-dev:nightly
  model: moonshotai/Kimi-K2-Thinking
  model-prefix: kimik2think
  runner: mi355x-m15-17
  precision: int4
  framework: NA
  multinode: false
  seq-len-configs:
  - isl: 1024
    osl: 1024
    search-space:
    - { tp: 8, conc-start: 4, conc-end: 128 }

glm4p7-fp4-mi355x-vllm:
  image: rocm/vllm-dev:nightly
  model: zai-org/GLM-4.7-FP8
  model-prefix: glm4p7
  runner: mi355x-m15-17
  precision: fp4
  framework: NA
  multinode: false
  seq-len-configs:
  - isl: 1024
    osl: 1024
    search-space:
    - { tp: 8, conc-start: 4, conc-end: 128 }

dsv32-fp8-mi355x-vllm:
  image: rocm/vllm-dev:nightly
  model: deepseek-ai/DeepSeek-V3.2
  model-prefix: dsv32
  runner: mi355x-m15-17
  precision: fp8
  framework: vllm
  multinode: false
  seq-len-configs:
  - isl: 128
    osl: 128
    search-space:
    - { tp: 8, conc-start: 4, conc-end: 128 }

dsocr-bf16-mi355x-vllm:
  image: rocm/vllm-dev:nightly
  model: deepseek-ai/DeepSeek-OCR
  model-prefix: dsocr
  runner: mi355x-m15-17
  precision: bf16
  framework: NA
  multinode: false
  seq-len-configs:
  - isl: 1024
    osl: 1024
    search-space:
    - { tp: 2, conc-start: 4, conc-end: 128 }

minimaxm2p1-fp8-mi355x-vllm:
  image: rocm/vllm-dev:nightly
  model: MiniMaxAI/MiniMax-M2.1
  model-prefix: minimaxm2p1
  runner: mi355x-m15-17
  precision: fp8
  framework: NA
  multinode: false
  seq-len-configs:
  - isl: 1024
    osl: 1024
    search-space:
    - { tp: 4, conc-start: 4, conc-end: 128 }



qwen3.235b-fp8-mi355x-sglang:
  image: lmsysorg/sglang:v0.5.7-rocm700-mi35x
  model: Qwen/Qwen3-235B-A22B-Instruct-2507-FP8
  model-prefix: qwen3.235b
  runner: mi355x-m15-17
  precision: fp8
  framework: NA
  multinode: false
  seq-len-configs:
  - isl: 128
    osl: 128
    search-space:
    - { tp: 4, conc-start: 4, conc-end: 4 }

qwencoder3.480b-fp8-mi355x-sglang:
  image: lmsysorg/sglang:v0.5.7-rocm700-mi35x
  model: Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8
  model-prefix: qwencoder3.480b
  runner: mi355x-m15-17
  precision: fp8
  framework: sglang
  multinode: false
  seq-len-configs:
  - isl: 1024
    osl: 1024
    search-space:
    - { tp: 4, conc-start: 4, conc-end: 128 }

kimik2.inst0905-fp8-mi355x-sglang:
  image: lmsysorg/sglang:v0.5.7-rocm700-mi35x
  model: moonshotai/Kimi-K2-Instruct-0905
  model-prefix: kimik2.inst0905
  runner: mi355x-m15-17
  precision: fp8
  framework: NA
  multinode: false
  seq-len-configs:
  - isl: 128
    osl: 128
    search-space:
    - { tp: 8, conc-start: 4, conc-end: 4 }

kimik2think-int4-mi355x-sglang:
  image: lmsysorg/sglang:v0.5.7-rocm700-mi35x
  model: moonshotai/Kimi-K2-Thinking
  model-prefix: kimik2think
  runner: mi355x-m15-17
  precision: int4
  framework: NA
  multinode: false
  seq-len-configs:
  - isl: 128
    osl: 128
    search-space:
    - { tp: 8, conc-start: 4, conc-end: 4 }

glm4p7-fp4-mi355x-sglang:
  image: lmsysorg/sglang:v0.5.7-rocm700-mi35x
  model: zai-org/GLM-4.7-FP8
  model-prefix: glm4p7
  runner: mi355x-m15-17
  precision: fp4
  framework: NA
  multinode: false
  seq-len-configs:
  - isl: 128
    osl: 128
    search-space:
    - { tp: 8, conc-start: 4, conc-end: 4 }

dsv32-fp8-mi355x-sglang:
  image: lmsysorg/sglang:v0.5.7-rocm700-mi35x
  model: deepseek-ai/DeepSeek-V3.2
  model-prefix: dsv32
  runner: mi355x-m15-17
  precision: fp8
  framework: NA
  multinode: false
  seq-len-configs:
  - isl: 128
    osl: 128
    search-space:
    - { tp: 8, conc-start: 4, conc-end: 4 }

dsocr-bf16-mi355x-sglang:
  image: lmsysorg/sglang:v0.5.7-rocm700-mi35x
  model: deepseek-ai/DeepSeek-OCR
  model-prefix: dsocr
  runner: mi355x-m15-17
  precision: bf16
  framework: NA
  multinode: false
  seq-len-configs:
  - isl: 128
    osl: 128
    search-space:
    - { tp: 2, conc-start: 4, conc-end: 4 }

minimaxm2p1-fp8-mi355x-sglang:
  image: lmsysorg/sglang:v0.5.7-rocm700-mi35x
  model: MiniMaxAI/MiniMax-M2.1
  model-prefix: minimaxm2p1
  runner: mi355x-m15-17
  precision: fp8
  framework: NA
  multinode: false
  seq-len-configs:
  - isl: 128
    osl: 128
    search-space:
    - { tp: 4, conc-start: 4, conc-end: 4 }